name: Discord

on:
  push:
    branches:
      - main
  schedule:
    - cron: "50 9 * * *"

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.openai_api_key }}
          DISCORD_TOKEN: ${{ secrets.discord_token }}
          DISCORD_CHANNEL_ID: ${{ secrets.discord_channel_id }}
        run: |
          node index.js
